=== CarlosGomez504/0373-RA4Pr1-XML-validos-Carlos-Gomez/EX2/alumne.dtd
<!ELEMENT alumne (nom, cognom, telefon?, email?, modul+)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT modul (#PCDATA)>
<!ATTLIST alumne id CDATA #REQUIRED
tipus (presencial | distancia) #REQUIRED>

=== CarlosGomez504/0373-RA4Pr1-XML-validos-Carlos-Gomez/EX2/alumne.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumne SYSTEM "alumne.dtd">

<alumne id="CG-2026" tipus="distancia">

  <nom>Carlos</nom>
  <cognom>Gómez</cognom>

  <telefon>664726777</telefon>
  <email>cgomezh25@ilb.cat</email>

  <modul>Llenguatges de Marques</modul>
  <modul>Sistemes Informàtics</modul>
  <modul>Bases de Dades</modul>

</alumne>
