=== CarlosGomez504/0373-RA4Pr1-XML-validos-Carlos-Gomez/EX3/activitats.dtd
<!ELEMENT activitats (activitat+)>

<!ELEMENT activitat (nom, monitor, horari?, participant+, lloc)>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT monitor (#PCDATA)>
<!ELEMENT horari (#PCDATA)>
<!ELEMENT participant (#PCDATA)>

<!ELEMENT lloc (interior | exterior)>
<!ELEMENT interior (#PCDATA)>
<!ELEMENT exterior (#PCDATA)>

<!ATTLIST activitat 
          codi CDATA #REQUIRED
          tipus (esportiva | artistica) #REQUIRED>

=== CarlosGomez504/0373-RA4Pr1-XML-validos-Carlos-Gomez/EX3/activitats.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE activitats SYSTEM "activitats.dtd">
<activitats>
    
    <activitat codi="DEPORTE" tipus="esportiva">
        <nom>Baloncesto Sabadell</nom>
        <monitor>Ricardo Gómez</monitor>
        <horari>Martes y Jueves a las 18:00</horari>
        <participant>Carlos Gómez</participant>
        <participant>Sergio Ruiz</participant>
        <lloc>
            <interior>Pabellón Municipal</interior>
        </lloc>
    </activitat>
    
    <activitat codi="MUSICA" tipus="artistica">
        <nom>Guitarra Española</nom>
        <monitor>Elena Martínez</monitor>
        <participant>Lucía Fernández</participant>
        <lloc>
            <interior>Aula de Música</interior>
        </lloc>
    </activitat>
    
</activitats>
