=== CarlosGomez504/0373-RA4Pr1-XML-validos-Carlos-Gomez/EX5/persona.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="persona">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nom" type="xs:string"/>
                <xs:element name="edat" type="xs:integer"/>
                <xs:element name="ciutat" type="xs:string"/>
                <xs:element name="aficio" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="nivell">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="baix"/>
                            <xs:enumeration value="mitja"/>
                            <xs:enumeration value="alt"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="dni" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== CarlosGomez504/0373-RA4Pr1-XML-validos-Carlos-Gomez/EX5/persona.xml
<?xml version="1.0" encoding="UTF-8"?>
<persona dni="G559130" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="persona.xsd">
    
    <nom>Carlos</nom>
    <edat>22</edat>
    <ciutat>Sabadell</ciutat>
    
    <aficio>Series</aficio>
    <aficio>Computadoras</aficio>
    <aficio>Futbol</aficio>
    <aficio>Comer</aficio>
    <aficio>Escuchar musica</aficio>
    
    <nivell>alt</nivell>
    
</persona>
